a1/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path, re_path
from wordbucket import views
from wordbucket import urls as wordbucket_urls

urlpatterns = [
    path('', include(wordbucket_urls)),
    path('admin/', admin.site.urls),
]

wordbucket/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from wordbucket import views

app_name = 'wordbucket'
urlpatterns = [
    path('', views.home_page, name='home'),
    path('add_word', views.add_word, name='add_word'),
    re_path(r'^search/(\w+)$', views.search, name='search'),
    re_path(r'^(\d+)/$', views.view_word, name='detail'),
    re_path(r'^(\d+)/add_explanation$', views.add_explanation, name='add_explanation'),
    re_path(r'^(\d+)/like$', views.vote_like, name='like'),
    re_path(r'^(\d+)/dislike$', views.vote_dislike, name='dislike'),
    
    # auth part
    re_path(r'^signup/$', views.signup, name='signup'),
    re_path(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    re_path(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),

    # csv
    re_path(r'^(\d+)/import$', views.import_csv, name='import'),
    re_path(r'^(\d+)/export$', views.export_csv, name='export'),
]

wordbucket/models.py
from datetime import datetime
from django.db import models
from django.utils import timezone

class Word(models.Model):
    #word (text)
    word = models.TextField(default='')
    date_pub = models.DateTimeField(default=datetime.now, blank=True)
    def __str__(self):
        return self.word
    def was_published_recently(self):
        return self.date_pub >= timezone.now() - datetime.timedelta(days=1)

class Explanation(models.Model):
    #foreign key
    word = models.ForeignKey(Word, on_delete=models.CASCADE)
    explanation_text = models.CharField(max_length=600)
    votes_like = models.IntegerField(default=0)
    votes_dislike = models.IntegerField(default=0)
    def __str__(self):
        return self.explanation_text
    def __int__(self):
        return self.votes_like
    def __int__(self):
        return self.votes_dislike

class Like(models.Model):
    #foreign key for Like and Dislike
    explanation = models.ForeignKey(Explanation, on_delete=models.CASCADE)
    #user votes count
    user_like = models.TextField(default='')
    def __str__(self):
        return self.user_like

class Dislike(models.Model):
    #foreign key for Like and Dislike
    explanation = models.ForeignKey(Explanation, on_delete=models.CASCADE)
    #user votes count
    user_dislike = models.TextField(default='')
    def __str__(self):
        return self.user_dislike

wordbucket/views.py
from django.shortcuts import redirect, render, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from wordbucket.models import Word, Explanation, Like, Dislike
import string, csv, os, codecs
from django.http import HttpResponse
from io import TextIOWrapper

def home_page(request):
    d_message = ""
    words = Word.objects.order_by('-date_pub')[:5]
    alphabets = string.ascii_lowercase
    return render(request, 'home.html', {'words': words, 'd_message': d_message, 'alphabets': alphabets})

def view_word(request, word_id):
    d_message = ""
    word_ = Word.objects.get(id=word_id)
    like_ = Like.objects.all
    dislike_ = Dislike.objects.all
    return render(request, 'detail.html', {'word': word_, 'like': like_, 'dislike': dislike_, 'd_message': d_message})

def add_word(request):
    d_message = ""
    words = Word.objects.order_by('-date_pub')[:5]
    word_reference = str(request.POST['word_input'])
    explanation_reference = str(request.POST['explanation_input'])
    # query for duplicate word
    d_query = Word.objects.filter(word=word_reference)
    if (not d_query) and (word_reference != '') :
        word_ = Word.objects.create(word = request.POST['word_input'])
        explanation_ = Explanation.objects.create(explanation_text=request.POST['explanation_input'], votes_like = 0, votes_dislike = 0, word=word_)
        return redirect('/')
    else :
        word_ = Word.objects.get(word=word_reference)
        d_query2 = Explanation.objects.filter(explanation_text=explanation_reference, word=word_)
        if (word_reference != '') and (not d_query2) :
            # duplacate word id
            dword_id = Word.objects.get(word = word_reference)
            explanation_ = Explanation.objects.create(explanation_text=request.POST['explanation_input'], votes_like = 0, votes_dislike = 0, word=dword_id)
            d_message = "duplicate word, your explanation add to existing word."
        else :
            d_message = "please enter the word"
        alphabets = string.ascii_lowercase
        return render(request, 'home.html', {'words': words, 'd_message': d_message, 'alphabets': alphabets})

def add_explanation(request, word_id):
    word_ = Word.objects.get(id=word_id)
    explanation_reference = str(request.POST['explanation_input'])
    # query for duplicate explanation
    d_query = Explanation.objects.filter(explanation_text=explanation_reference, word=word_)
    if (not d_query) and (explanation_reference != '') :
        explanation_ = Explanation.objects.create(explanation_text=request.POST['explanation_input'], votes_like = 0, votes_dislike = 0, word=word_)
        return redirect('/%d/' % (word_.id,))
    else :
        d_message = "duplicate or null explanation, please enter new explanation."
        return render(request, 'detail.html', {'word': word_, 'd_message': d_message})
        
def search(request, word_search):    
    word_reference = 'no'
    if request.method == 'POST':
        word_reference = str(request.POST['search_input'])
    
    if word_reference != 'no' :
        word_found = Word.objects.filter(word__contains=word_reference)
        if not word_found :
            message = "WORD not found"
            return render(request, 'search.html', {'message': message})
        else :
            return render(request, 'search.html', {'word_found': word_found})
    else :
        word_found = Word.objects.filter(word__startswith=word_search)
        if not word_found :
            message = "WORD not found"
            return render(request, 'search.html', {'message': message})
        else :
            return render(request, 'search.html', {'word_found': word_found})

def vote_like(request, explanation_id):
    explanation_ = Explanation.objects.get(id=explanation_id)    
    if request.user.is_authenticated:
        d_query = Like.objects.filter(user_like=request.user.username, explanation=explanation_)
        if not d_query :
            Like.objects.create(user_like=request.user.username, explanation=explanation_)
            selected_explanation = explanation_.like_set.all()
            vote_like_ = selected_explanation.count()
            explanation_.votes_like = vote_like_
            explanation_.save()
    return HttpResponseRedirect(reverse('wordbucket:detail', args=(explanation_.word.id,)))

def vote_dislike(request, explanation_id):
    explanation_ = Explanation.objects.get(id=explanation_id)    
    if request.user.is_authenticated:
        d_query = Dislike.objects.filter(user_dislike=request.user.username, explanation=explanation_)
        if not d_query :
            Dislike.objects.create(user_dislike=request.user.username, explanation=explanation_)
            selected_explanation = explanation_.dislike_set.all()
            vote_dislike_ = selected_explanation.count()
            explanation_.votes_dislike = vote_dislike_
            explanation_.save()
    return HttpResponseRedirect(reverse('wordbucket:detail', args=(explanation_.word.id,)))

# auth. part

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})

# csv part

def export_csv(request, word_id):
    output = []
    word_ = Word.objects.get(id=word_id)
    selected_word = word_.explanation_set.all()
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename= "export.csv"'
    
    writer = csv.writer(response)
    writer.writerow(['word', 'explanation'])
    
    for word in selected_word:
        output.append([word.word, word.explanation_text])

    writer.writerows(output)
    return response

def import_csv(request, word_id):
    word_ = Word.objects.get(id=word_id)
    if request.POST and request.FILES:
        csvfile = TextIOWrapper(request.FILES['csv_file'], encoding=request.encoding)
        reader = csv.reader(csvfile)
        next(reader)
        for row in reader:
            #duplicate explanation
            d_query = Explanation.objects.filter(explanation_text=row[1], word=word_)
            if (not d_query) and (row[1] != '') :
                explanation_ = Explanation.objects.create(explanation_text=row[1], votes_like = 0, votes_dislike = 0, word=word_)
    return HttpResponseRedirect(reverse('wordbucket:detail', args=(word_id,)))

wordbucket/templates/detail.html
<html>
    <head>
        <title>Word Bucket</title>
    </head>
    <body>
        <h1>Word Bucket</h1>
        {% if user.is_authenticated %}
          Hi {{ user.username }}!
          <p><a href="{% url 'wordbucket:logout' %}">logout</a></p>
        {% else %}
          You are not logged in
          <a href="{% url 'wordbucket:login' %}">LOGIN</a><br>
          You can not like and dislike. 
          <br>
        {% endif %}

        <h4>{{ d_message }}</h4>
        <form method="POST" id="form1" action="/{{ word.id }}/add_explanation">
            <input name="explanation_input" id="id_new_eplanation" placeholder="Add explanation" />
            {% csrf_token %}
        </form>
        <button type="submit" form="form1" value="Submit">Submit</button>

        <h2>{{ word }}</h2>

        <table id="id_explanation_table">
            {% for explanation in word.explanation_set.all %}
                <tr>
                    <td>explanation {{ forloop.counter }} : {{ explanation.explanation_text }}<br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        {{ explanation.votes_like }} &nbsp;<a href="{% url 'wordbucket:like' explanation.id %}">LIKE</a>
                        &nbsp; {{ explanation.votes_dislike }} &nbsp;<a href="{% url 'wordbucket:dislike' explanation.id %}">DISLIKE</a>
                    <br><br>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <br>
        {% if user.is_authenticated %}
            {% if user.get_username == 'admin' %}
        <a href="{% url 'wordbucket:export' word.id %}">export</a><br><br>
        <form action="{% url 'wordbucket:import' word.id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name="csv_file" />
            <input type="submit" value="Upload" />
        </form>
            {% endif %}
        {% endif %}
        <a href="{% url 'wordbucket:home' %}">HOME</a>
    </body>
</html>

wordbucket/templates/home.html
<html>
    <head>
        <title>Word Bucket</title>
    </head>
    <body>
        <h1>Word Bucket</h1>
        {% if user.is_authenticated %}
          Hi {{ user.username }}!
          <p><a id="logout" href="{% url 'wordbucket:logout' %}">logout</a></p>
        {% else %}
          You are not logged in
          <a id="login" href="{% url 'wordbucket:login' %}">LOGIN</a> or <a id="signup" href="{% url 'wordbucket:signup' %}">SIGNUP</a>
          <br>
        {% endif %}

        <br>browse<br>
            {% for alphabet in alphabets %}
                <a href="{% url 'wordbucket:search' alphabet %}">{{ alphabet }}</a>&nbsp;
            {% endfor %}
        <br>
        <h4>{{ d_message }}</h4>
        <form method="POST" id="form1" action="/add_word">
            <input name="word_input" id="id_new_word" placeholder="Add new word" />
            <input name="explanation_input" id="id_new_eplanation" placeholder="Add explanation" />
            {% csrf_token %}
        </form>
        <button type="submit" form="form1" value="Submit">Submit</button>

        <table id="id_word_table">
            {% for word in words %}
                <tr><td id="word.word"><a href="{% url 'wordbucket:detail' word.id %}">{{ word.word }}</a></td></tr>
            {% endfor %}
        </table>
        <br>
        <form action = "/search/byword" id="form_search" method="POST">
            <input tpye="text" id="id_search" name = "search_input" placeholder="Search word" />
            <input type = "submit" form="form_search" value = "Search">
            {% csrf_token %}
        </form>
        
    </body>
</html>

wordbucket/templates/login.html
<html>
    <head>
        <title>Word Bucket : LOGIN</title>
    </head>
    <body>
        <h1>Word Bucket</h1>
        <br><h2><a href="{% url 'wordbucket:login' %}">LOGIN</a></h2><br>

          <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Login</button>
          </form>
          <a href="{% url 'wordbucket:home' %}">HOME</a>

    </body>
</html>

wordbucket/templates/search.html
<html>
    <head>
        <title>Word Bucket</title>
    </head>
    <body>
        
       <h1>Search Word Bucket </h1>
        {% if user.is_authenticated %}
          Hi {{ user.username }}!
          <p><a href="{% url 'wordbucket:logout' %}">logout</a></p>
        {% else %}
          You are not logged in
          <a href="{% url 'wordbucket:login' %}">LOGIN</a>
          <br><br>
        {% endif %}
       <form action = "/search/byword" method="POST">
            <input tpye="text" name = "search_input" placeholder="Search word" />
            <br>
            <input type = "submit" value = "Submit">
            {% csrf_token %}
        </form>
        {% if message %}
            <p>{{ message }}</p>
        {% endif %}       
        
        {% if word_found %}
            <table id="id_word_table">
            {% for word in word_found %}
                <tr><td id="word.word"><a href="{% url 'wordbucket:detail' word.id %}">{{ word.word }}</a></td></tr>
            {% endfor %}
        </table>
        {% endif %} 

        <br>
        <a href="{% url 'wordbucket:home' %}">HOME</a>
    </body>
</html>

wordbucket/templates/signup.html
<html>
    <head>
        <title>Word Bucket : LOGIN</title>
    </head>
    <body>
        <h1>Word Bucket</h1>
        <h2>Sign up</h2>
          <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Sign up</button>
          </form>
          <a href="{% url 'wordbucket:home' %}">HOME</a>

    </body>
</html>